---
- name: Install PostgreSQL on Debian-based systems
  hosts: postgres_servers
  become: yes
  gather_facts: yes

  roles:
    - Install Prerequisites
    - Ensure_Sudo_is_Installed
    - Install_PostgreSQL_Common_Package
    - Ensure_PGDG_Directory_Exists
    - Download_PostgreSQL_Repository_Key
    - Add_PostgreSQL_APT_Repository
    - Update_APT_Cache
    - Install_PostgreSQL
    - Display_PostgreSQL_Version
    - Print_PostgreSQL_Version

  handlers:
    - name: Restart PostgreSQL
      service:
        name: postgresql
        state: restarted
