---
- name: Install PostgreSQL on Debian-based systems
  hosts: postgres_servers
  become: yes
  gather_facts: yes

  roles:
    - Install Prerequisites
    - Ensure Sudo is Installed
    - Install PostgreSQL Common_Package
    - Ensure PGDG Directory Exists
    - Download PostgreSQL Repository_Key
    - Add PostgreSQL APT Repository
    - Update APT Cache
    - Install PostgreSQL
    - Display PostgreSQL Version
    - Print PostgreSQL Version

  handlers:
    - name: Restart PostgreSQL
      service:
        name: postgresql
        state: restarted
