---
- name: Install PostgreSQL on Debian-based systems
  hosts: postgres_servers
  become: yes

  tasks:
  - include_tasks: tasks/install_prerequisites.yml
  - include_tasks: tasks/ensure_sudo.yml
  - include_tasks: tasks/install_postgresql_common.yml
  - include_tasks: tasks/ensure_pgdg_directory.yml
  - include_tasks: tasks/download_postgresql_key.yml
  - include_tasks: tasks/add_postgresql_repository.yml
  - include_tasks: tasks/update_apt_cache.yml
  - include_tasks: tasks/install_postgresql.yml
  - include_tasks: tasks/display_postgresql_version.yml
  - include_tasks: tasks/print_postgresql_version.yml

  handlers:
  - include_tasks: tasks/restart_postgresql.yml
