---
- name: Install PostgreSQL on Debian-based systems
  hosts: postgres_servers
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes

roles:
   - Install Prerequisites
   - Ensure Sudo is Installed
   - Install PostgreSQL Common Package
   - Ensure PGDG Directory Exists
   - Download PostgreSQL Repository Key
   - Add PostgreSQL APT Repository
   - Update APT Cache
   - Install PostgreSQL
   - Display PostgreSQL Version
   - Print PostgreSQL Version
   

  handlers:
  - include_tasks: tasks/restart_postgresql.yml
